language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: CJiC9QVQMOtVU7TL2c+HPYThQCdyW37kaVu+OXXKipUmyDzH6srWPzt+vsQBYkrzSSQT+3aEHeZlEcB9yeDr8nMi7LsDHESMkazV9rFGf/167HZST+OMKjxXFfwJT5qgIdXIjD6l2j6bEoziQ0OkcShuMWVK0YHXlgAgokDzlVbKH4dQbAfKVYolCvamE6eir0K2sOMIF5SzNTRj/2BcHsDQJ+/33HnJ22TSh9fAFTXX/Y2SHkYluAjdrJTI0BFkhASDDpWOqXlyzrWTUx/oXuSj2x8gCC2agdCE7i4ep9bQoHZRW8bH9yP6UFQDdqcOirmOTvOysEzyGdV5VkNZEYroyAEjx2wut5abpV6UDVmJFSrNneImE+O8jyFHRbVKeV4ZFzxKS9VLeDdudRmECtV4iS/593D3yWTMuOP6B8L2DhfkwYOJf95wUD7g93AdYteZYkcDGNv8T2oEYrlAMcyN+EYfX7Kk7X0SalnPRi3WIXzbD5b7tQYtUUhUAgrqzC/6Om4exjikqrb9ym5fJJS4glV2FwaKEYeuiP+0CGO6RN8NtZ23bOArCPtgu9Znq/VN1TFrq1vrngremnmcosifyQhPFjF0SVqU/01SfWotZLgyPVRrSnFBqM74bEFFHsrJiwUaEvpbKKqrTX9ZIZSmXQcQrAeytQn3ZZtSrSM=
